apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-runner
  labels:
    app: github-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-runner
  template:
    metadata:
      labels:
        app: github-runner
    spec:
      containers:
      - name: github-runner
        image: sanderknape/github-runner:latest
        env:
        - name: GITHUB_OWNER
          value: your-organization
        - name: GITHUB_APP_ID
          value: 12345
        volumeMounts:
          - name: privatekey
            mountPath: '/certs'
            readOnly: true
    volumes:
      - name: privatekey
        secret:
          secretName: github-runner-app-private-key
# create secret with:
# kubectl create secret generic github-runner-app-private-key --from-file=private-key=./private-key.cer
